name: 'ftp-action'
author: 'Sebastian Popp <ftp-action@sebastianpopp.com>'
description: 'Automate copying your files via FTP using this GitHub action.'
inputs:
  host:
    description: 'FTP host'
    required: true
  user:
    description: 'FTP user'
    required: true
  password:
    description: 'FTP password'
    required: true
  forceSsl:
    description: 'Force SSL encryption'
    required: false
    default: 'false'
  sslAuth:
    description: 'The  argument for AUTH command, can be one of SSL, TLS, TLS-P, TLS-C.  See RFC4217 for explanations. By default TLS or SSL will be used, depending on FEAT reply.'
    required: false,
    default: ''
  localDir:
    description: 'Local directory'
    required: false
    default: '.'
  remoteDir:
    description: 'Remote directory'
    required: false
    default: '.'
  initialProt:
    description: 'Specifies initial PROT setting for FTPS connections. Should be one of: C, S, E, P,  or empty. Default is empty which means unknown, so that lftp will use PROT command unconditionally. If PROT command turns out to be unsupported,  then  Clear  mode  would  be assumed.'
    required: false,
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  color: 'blue'
  icon: 'upload-cloud'
